### ISSUE TITLE
Issue generating correct repository key tpye

### ISSUE THREAD

**Issue by sandycomp** [GaetanoPiazzolla/springboot-3layer-generator#1]
An issue in generating a repository class using the latest version. I have below table in MySQL.
CREATE TABLE `contacts` (
  `CONTACT_ID` smallint(6) NOT NULL,
  `DESCR` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`CONTACT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8.

The repository generated as below 
public interface ContactModesRepository extends JpaRepository<ContactModes, **java.lang.String**> {
}

I think the repository should have a key as java.lang.Short, instead it's generated as java.lang.String.

I'm observing similar issue across other tables, For example the entity class have value as java.lang.Long, but repository class key is java.lang.String.

Please help here.

**Comment by GaetanoPiazzolla** [comment]
Hello Sandy, the generation starts from the class, so if the id of the class Is a short, the repository Will have a short as well.
