### ISSUE TITLE
Some enhancements and suggestions

### ISSUE THREAD

**Issue by MostafaRamadan1** [GaetanoPiazzolla/springboot-3layer-generator#2]
First of all let me **praising** and **appreciate** the effort done in this **amazing** plugin, here are some points that I believe it will make it more awesome :

- Adding options to generate ControllersDto only or with Controller using entity, as best and common practices, most of developers don't want to expose their entity/db schema in public. (Yaml configuration)
- Adding options to generate the `CrudController` Interface or not (Yaml configuration).
- Adding options to generate the `CrudService` Interface or not (Yaml configuration).
- Adding options to specify the `dto` location package.
- Adding options to specify the `mapper` location package.
- Adding documentation to ensure build project first before running the plugin command. or just update the command to be `./gradlew clean build layer3gen `
- In `CrudController` all read operation should be in get verb(common convention), but I found @PostMapping("find") and also passing the entity itself, I don't have any clue what is the use for this entity. Pageable rest api, should only take the `page` and `size` parameters, also to mention findAll method not need to pass the example, `Example<User> example = Example.of(entity);` you can just say `repository.findAll(pageable);` without passing example object.
- In generated dto found two not needed imports 
- `import org.springframework.data.domain.Page; mport org.springframework.data.domain.Pageable;`
- In readOne, in service layer, `repository.getOne(primaryKey);` getOne is deprecated method and will be removed soon, instead use findById and return Optional object is more common.

**Comment by MostafaRamadan1** [comment]
I have done all the enhancements and more, in a forked project, and created a pull request in your repo.

**Comment by GaetanoPiazzolla** [comment]
Thanks!!

Il giorno sab 18 feb 2023 alle 09:34 Mostafa Ramadan <
***@***.***> ha scritto:

**Comment by GaetanoPiazzolla** [comment]
Completed in release 1.9, not for the example entity query that I restored.
